@adminurl=http://localhost:8081
@expression = instance.variables.start.request.DEVICE_NAME_OR_MODEL
@value= TFYLX3

###

POST {{adminurl}}/evaluate?exp={{expression}}
Content-Type: application/json

{
  "expression": "serie",
  "data": {
    "serie": "TFYLX3",
    "DEVICE_MODEL": "TFYLX3",
    "nested": { "model": "TFYLX3" },
    "list": [ { "device": "TFYLX3" }, { "other": "123" } ]
  }
}

###

POST {{adminurl}}/evaluate/get-expression/{{value}}
Content-Type: application/json

< ./files/test.json